### ISSUE TITLE
Is it a right way to enable the deploy-rs multi-arch support

### ISSUE THREAD

**Issue by GTrunSec** [divnix/digga#18]
This issue PR related to https://github.com/GTrunSec/digga/commit/3eec43be5b886599cc5d80296d0b090132eb061c. I'm not sure this way would be the right solution here.

## Would your feature fix an existing issue?
using digga.lib.mkDeployNodes with multi-arch 

## Describe the solution you'd like

Adding dpeloy-rs multi-arch support.
Adding hostname of deploy-rs alternative option, as following:

- Hostname: NixOS
- using networking.domain or networking.hostname ()
Deploy-rs hostname: "10.110.110.1"  (IP address as hostname of deploy-rs)

**Comment by blaggacao** [comment]
Good question, on the surface, it looks to me as if deploy-rs.lib happens to be system-specific because of:

` [`self.defaultPakcage` invocation](https://github.com/serokell/deploy-rs/blob/896f9d3b5d7c0dc2566c7d2c6fe854ecef17daec/flake.nix#L94)

among a bunch of other non-system specific usages of pkgs:

- [`pkgs.buildEnv`](https://github.com/serokell/deploy-rs/blob/896f9d3b5d7c0dc2566c7d2c6fe854ecef17daec/flake.nix#L65)
- [`pkgs.writeTextFile`](https://github.com/serokell/deploy-rs/blob/896f9d3b5d7c0dc2566c7d2c6fe854ecef17daec/flake.nix#L70)
- [`pkgs.runtimeShell`](https://github.com/serokell/deploy-rs/blob/master/flake.nix#L73)
- [`pkgs.writeScript`](https://github.com/serokell/deploy-rs/blob/896f9d3b5d7c0dc2566c7d2c6fe854ecef17daec/flake.nix#L82)

So making it system-depended seems right.

---

I'm doubtful about:
```nix
{
          hostname =
            if config.config.networking.domain != null
            then config.config.networking.domain else config.config.networking.hostName;
}
```

What is the rationale behind doing this?

**Comment by GTrunSec** [comment]
>  Adding hostname of deploy-rs alternative option, as following:
Deploy-rs hostname: "10.110.110.1" (IP address as hostname of deploy-rs)


- default setting: `error: cannot connect to 'root@infra-vbox''`
- I would like to use an IP address as ssh connection without modifying hosts.
    networking.domain = "10.220.170.112";   

```
deploy.nodes.infra-vbox= {    
  hostname = "10.220.170.126";   
   profiles.main = {        
    user = "root";      
    sshUser = "root";      
    path = deploy-rs-flake.lib.x86_64-linux.activate.nixos          
   self.nixosConfigurations.infra-vbox;  
    }; };
```
-

**Comment by blaggacao** [comment]
> I would like to use an IP address as ssh connection without modifying hosts.
networking.domain = "10.220.170.112"

I see. I [had the same issue](https://github.com/serokell/deploy-rs/issues/75).

The current work around it to use [`--hostname` command override](https://github.com/serokell/deploy-rs/blob/f0456d67149edbf27a6cb0a4963386bc2e678267/src/bin/deploy.rs#L549). A better upstream implementation would be eventually mandatory, though.

**Comment by GTrunSec** [comment]
Thanks, I'm going to waiting for this implementation.

**Comment by blaggacao** [comment]
I think though the deploy-rs multi-arch fix is still valid and merits proposal via PR.

**Comment by GTrunSec** [comment]
> The current work around it to use --hostname

the flag of --hostname seems does not to work with more than one machine.

Overriding the hostname still important to me.  one of the custom solutions is to add the option of deploy-rs to digga.lib without t modifying networking as following:

```nix
 if config.config.host.deploy-rs.hostName != null
=  28 │ │ │ │ │ │ then config.config.host.deploy-rs.hostName else config.config.networking.hostName;      

1 
  10 │ options.host = with lib;
   9 │ │ {
   8 │ │ │ username = mkOption {
   7 │ │ │ │ type = types.str;
   6 │ │ │ │ default = machine.username;
   5 │ │ │ │ description = "hosts username";
   4 │ │ │ };
   3 
   2 │ │ │ deploy-rs.hostName = mkOption {
   1 │ │ │ │ type = types.str;
  17 │ │ │ │ default = machine.interface.default.ip;                                                                     
   1 │ │ │ │ description = "override deploy-rs hostName";
   2 │ │ │ };
```

**Comment by Pacman99** [comment]
This can be closed right?
