### ISSUE TITLE
NixOS Veteran Migration

### ISSUE THREAD

**Issue by blaggacao** [divnix/digga#25]
We might consider to allow:

- `./hosts/hostname/configuration.nix`
- `./hosts/hostname/default.nix`

When NixOS Veteran "Jeff" wants to migrate, they can get a devos based system identical to their current setup by just moving the contents of `/etc/nixos` into `./hosts/hostname/` and then start factoring slowly from there, one piece at a time.

@Radvendii

**Comment by Radvendii** [comment]
`rakeLeaves` makes `default.nix` work, though it doesn't affect `configuration.nix`. Not sure if it's worth special-casing that. I think requiring people to add a `default.nix` shim isn't such a big ask.

Basically it's a trade off between slightly cleaner conceptual model and code vs. slightly cleaner migration UX.

**Comment by Pacman99** [comment]
Agreed I think the `default.nix` requirement is ok. Although with #32 I think a `configuration.nix` would actually work, but the hostname would become "configuration". I guess thats an advantage, since we support just copying `/etc/nixos` over to the host folder, but its very obvious that it should be modified soon.

**Comment by blaggacao** [comment]
Jep, we can close this through current state of `develop`.

No direct support for `./configuration.nix`
Please rename to `./default.nix` or make a shim.

Folder name = hostname.
