### ISSUE TITLE
Call for Maintainers

### ISSUE THREAD

**Issue by nrdxp** [divnix/digga#400]
While @blaggacao, @Pacman99 and myself have become busier with personal obligations, we've noticed a lag in our ability to maintain the project. There are several members of the community besides ourselves who have been very active, and we'd be more than happy for the help if anyone is up to the task. Please feel free to drop a reply in this issue if you'd like to help!

**Comment by Princemachiavelli** [comment]
Does this apply to the related divnix projects; digga and bud? I currently use devos in several production projects and have plans for more so I certainly have a vested interest in keeping everything functional.

Since I haven't directly contributed more than the occasional bug report I'm may not be the best fit for a maintainer currently but I have started reviewing many of the open tickets & PRs. I can certainly help work through those.

I'm not sure what the current roadmap or priorities for devos/divnix are but there are a few areas I will be looking into:

## Better home-manager integration and user management.

* Taking advantage of any upstream home-manager improvements like proper 2.4 profile support, etc.
* Making the usage of portable HM users and system users a bit cleaner would be nice.
* (Mostly a home-manager issue) Provide a unified way to define a user's SSH authorized keys for both system users and portable users.
* Documenting a method for setting home-manager defaults.
* Support for LDAP/unknown/generic users.


## Deployment improvements
* (Mostly an deploy-rs issue) Adding support password protected SUDO/privileges escalation methods.
* Workflow for automatically updating the nixpkgs inputs so Nix's autoUpgrade feature can install routine package updates. 
* Possible bud improvements or integration with makes (at least once it gets proper flake support).

**Comment by nrdxp** [comment]
yes, I should have clarified that in the original announcement, but this is geared toward maintainership of digga as well.

**Comment by Pacman99** [comment]
I do want to note that I don't plan to stop maintaining these projects. And I think the future of the projects are relatively secure. I use digga for a number of computers, so I have a stake in keeping them maintained. 

I can commit to dealing with bugfixes, updates, and PR reviews - they just might take me some time to get to. Over time I'll try to keep improving the documentation.
I think the main reason for this post is to find people who have the capacity to develop new features and get to those chores faster than we can.

**Comment by Pacman99** [comment]
We have a new maintainer onboard! Welcome @montchr :)

**Comment by montchr** [comment]
Thank you!
