### ISSUE TITLE
Use agenix in home-manager profiles

### ISSUE THREAD

**Issue by Sohalt** [divnix/digga#410]
Is it possible to use agenix secrets inside home-manager profiles?
As far as I can tell the home-manager profiles do not have access to the agenix module.

It would be very convenient to be able to access nixos options from home-manager profiles in general (though that would probably affect portability a littile).

**Comment by Pacman99** [comment]
Theres the agenix thread on this, https://github.com/ryantm/agenix/issues/50, and the project that implements home-manager agenix integration: https://github.com/jordanisaacs/homeage.

I wasn't planning to add homeage by default to devos, since its a separate flake, I figure anyone who needs it can just add the module themselves with `externalModules`.

**Comment by Sohalt** [comment]
Thanks for the pointers! That's super helpful!

03.01.2022 18:43:25 Parthiv Seetharaman ***@***.***>:

**Comment by Pacman99** [comment]
not much we can do in digga, users can import the homeage module in their flake and use that. If agenix itself adds a home-manager module then we could import that by default for home-manager profiles.
